### ISSUE TITLE
Develop "Multi-Core Machines" Simulator

### ISSUE THREAD

**Issue by henricasanova** [wrench-project/wrench-pedagogic-modules#11]
Input:
  - Number of cores:  (each is always 100 GFlop/sec)
  - Number of tasks
  - Flop amount per task (all the same)

Commandline:   argv[0] <num cores  (< 1000)> <num tasks> <GFlop>
 Example: ./mc_simulator 8 21 100

XML: one host with 1000 cores
  - WMS
  - BareMetalComputeService (uses <num cores> cores)

**Comment by willkoch** [comment]
Implemented simulation w/ variable number of cores, tasks, ram/task and gflop/task.
